package controller

const (
	READING_COURSE_TYPE_GD = 1
	ENGLISH_COURSE_TYPE_GD = 2
)

const (
	READING_COURSE_GD_MONEY = 19900
)

const (
	READING_COURSE_STATUS_START = iota
	READING_COURSE_STATUS_PAIED
	READING_COURSE_STATUS_REFUND
	READING_COURSE_STATUS_REFUND_NOT_AUTO
)
